### ISSUE TITLE
Regex version update?

### ISSUE THREAD

**Issue by rimutaka** [2fd/rust-regex-playground#1]
@2fd , would you consider a PR with an update to Rust deps?
I find your tool most useful, but it's too far out of date and has discrepancies with the latest Regex crate.

**Comment by 2fd** [comment]
sure, your contribution will be more than welcome 😄

**Comment by 2fd** [comment]
@rimutaka is the new version of the playground enough for you?

**Comment by rimutaka** [comment]
Fede, sorry, I am confused how it works now - you killed all the Rust code :) What is the Regex engine behind it all now?

**Comment by 2fd** [comment]
I moved it here: https://github.com/2fd/rregex
to have a better control over each version

**Comment by rimutaka** [comment]
Thanks Fede! :)
