### ISSUE TITLE
Add AST mode

### ISSUE THREAD

**Issue by crsov** [2fd/rust-regex-playground#244]
Currently, playground only shows HIR, having an option to view [regex-syntax AST](https://docs.rs/regex-syntax/latest/regex_syntax/ast/enum.Ast.html) as well would be great.

**Comment by 2fd** [comment]
Hi @crsov! That's going to take some work to implement and maintain, do you have any use case that warrants the effort?

**Comment by crsov** [comment]
> Hi @crsov! That's going to take some work to implement and maintain, do you have any use case that warrants the effort?

I would say no

**Comment by 2fd** [comment]
Ok, let's postpone this feature for some moment in the future. 

Thanks
